const type = {
    GET_DRIVER : "GET_DRIVER",
    SET_DRIVER : "SET_DRIVER",
    ERROR_DRIVER : "ERROR_DRIVER",
    GET_CONNECTION : "GET_CONNECTION",
    SET_CONNECTION : "SET_CONNECTION",
    ERROR_CONNECTION : "ERROR_CONNECTION",
    GET_TRUCKDETAIL : "GET_TRUCKDETAIL",
    SET_TRUCKDETAIL : "SET_TRUCKDETAIL",
    ERROR_TRUCKDETAIL : "ERROR_TRUCKDETAIL",
    GET_ALLITEMS : "GET_ALLITEMS",
    SET_ALLITEMS : "SET_ALLITEMS",
    ERROR_ALLITEMS : "ERROR_ALLITEMS",
    SET_LOGIN : "SET_LOGIN",
    GET_LOGIN : "GET_LOGIN",
    ERROR_LOGIN : "ERROR_LOGIN",
    SET_CREATEMORNINGACCEPTED : "SET_CREATEMORNINGACCEPTED",
    GET_CREATEMORNINGACCEPTED : "GET_CREATEMORNINGACCEPTED",
    ERROR_CREATEMORNINGACCEPTED : "ERROR_CREATEMORNINGACCEPTED",
    SET_SELECTEDTRUCKDETAIL : "SET_SelectedTruckDetail",
    GET_SELECTEDTRUCKDETAIL : "GET_SELECTEDTRUCKDETAIL",
    ERROR_SELECTEDTRUCKDETAIL : "ERROR_SELECTEDTRUCKDETAIL",
    UPDATE_MORNINGDATA : "UPDATE_MORNINGDATA",
    GET_MORNINGDATA : "GET_MORNINGDATA",
    ERROR_MORNINGDATA : "ERROR_MORNINGDATA",
    CLEAR_MORNINGDATA : "CLEAR_MORNINGDATA"
}

export {type};